name = "survive-korea"
main = "worker.js"
compatibility_date = "2026-07-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "survive-korea-ranks"
database_id = "4abdd935-9a98-4f60-b84b-53eece42e215"
